[package]
name = "attenuable-jwt"
authors = ["Adam Berger <adam@simplystated.dev>"]
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
base64 = "0.13.0"
jsonwebtoken = { version = "8.1.1", no-default-features = true }
ring = "0.16.20"
serde = "1.0.138"
thiserror = "1.0.31"
